### ISSUE TITLE
Exception on check4,  check_result reference

### ISSUE THREAD

**Issue by jacontre-c** [CiscoDevNet/sure#11]
INFO:#04:Check:vManage:CPU Count
ERROR:local variable 'check_result' referenced before assignment
Traceback (most recent call last):
  File "./sure.py", line 8528, in <module>
    check_result, check_analysis, check_action = criticalCheckfour(cpu_count, vedge_count, dpi_status, server_type)
  File "./sure.py", line 568, in criticalCheckfour
    return check_result, check_analysis, check_action
UnboundLocalError: local variable 'check_result' referenced before assignment

**Comment by rukapse** [comment]
Attached is the full log file. I think inside line 540 “if dpi_status == 'enable' and server_type == 'on-prem'” block we should have not only “if cpu_count < 32:”, but also some elif/else statement. Otherwise in case dpi_status == 'enable' and server_type == 'on-prem' and cpu_count == 32, we don’t set the check_result variable.
