### ISSUE TITLE
Unable to access Viptela-Shell from script for version 20.12

### ISSUE THREAD

**Issue by rukapse** [CiscoDevNet/sure#118]
Manage Password (Note: Tool doesn't support passwords containing "!") :

Traceback (most recent call last):
  File "[newsure.py](https://newsure.py/)", line 1954, in <module>
    version, version_tuple = vManageVersion()
  File "[newsure.py](https://newsure.py/)", line 316, in vManageVersion
    version_tuple =tuple([int(i) for i in version_tuple])
  File "[newsure.py](https://newsure.py/)", line 316, in <listcomp>
    version_tuple =tuple([int(i) for i in version_tuple])
ValueError: invalid literal for int() with base 10: ''
vmanage:~$

def showCommand(exec_mode_command):
    exec_mode_command = exec_mode_command+'\n'
    exec_mode_command = exec_mode_command.encode()
    p = subprocess.Popen('viptela_cli'.format(args.username), shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    p.stdin.write(exec_mode_command) #passing command
    stdOutput,stdError = p.communicate()
    p.stdin.close()
    return stdOutput.decode()

Manage Password (Note: Tool doesn't support passwords containing "!") :
> /home/admin/newsure.py(1955)<module>()
-> version, version_tuple = vManageVersion()
(Pdb) print(showCommand('show version'))

(Pdb) version=showCommand('show version')                                     
(Pdb) print(version)

(Pdb)

**Comment by UnspokenDrop7** [comment]
I have the same issue, also running Manager version 20.12.3.

Traceback (most recent call last):
  File "py3_sure.py", line 1953, in <module>
    version, version_tuple = vManageVersion()
  File "py3_sure.py", line 315, in vManageVersion
    version_tuple =tuple([int(i) for i in version_tuple])
  File "py3_sure.py", line 315, in <listcomp>
    version_tuple =tuple([int(i) for i in version_tuple])
ValueError: invalid literal for int() with base 10: ''
