### ISSUE TITLE
Error when running Sure on vManage 20.12.4

### ISSUE THREAD

**Issue by siqueirao** [CiscoDevNet/sure#138]
The following error occurs:

Critical Check:#03
ping: socket: Operation not permitted
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "py3_sure.py", line 1466, in wrapped_f
    ret = f(*args, **kwargs)
  File "py3_sure.py", line 1505, in criticalCheckseventeenpy3
    roundtrip = roundtrip_op[1]
IndexError: list index out of range

**Comment by ssidoret** [comment]
on python should change ping with nping to have it working		
output = executeCommand('ping -w 5 {} &'.format(vmanage_cluster_ip))
output = executeCommand('nping -w 5 {} &'.format(vmanage_cluster_ip))

**Comment by siqueirao** [comment]
Hi @ssidoret ! Tks!
 Then, because nping output is different, parsing also breaks:

Error:
******************
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "py3_sure.py", line 1449, in wrapped_f
    ret = f(*args, **kwargs)
  File "py3_sure.py", line 1488, in criticalCheckseventeenpy3
    roundtrip = roundtrip_op[1]
IndexError: list index out of range

***********************
Code:
1487:			roundtrip_op = output.split("time=")
1488:			roundtrip = roundtrip_op[1]

***************************
nping output
$ nping 9.9.9.9 -w 5

Starting Nping 0.7.80 ( https://nmap.org/nping ) at 2024-11-05 14:28 UTC
SENT (0.0013s) Starting TCP Handshake > 9.9.9.9:80
RCVD (0.0014s) Handshake with 9.9.9.9:80 completed
SENT (1.0025s) Starting TCP Handshake > 9.9.9.9:80
RCVD (1.0026s) Handshake with 9.9.9.9:80 completed
SENT (2.0036s) Starting TCP Handshake > 9.9.9.9:80
RCVD (2.0042s) Handshake with 9.9.9.9:80 completed
SENT (3.0053s) Starting TCP Handshake > 9.9.9.9:80
RCVD (3.0056s) Handshake with 9.9.9.9:80 completed
SENT (4.0067s) Starting TCP Handshake > 9.9.9.9:80
RCVD (4.0070s) Handshake with 9.9.9.9:80 completed

Max rtt: 0.608ms | Min rtt: 0.112ms | Avg rtt: 0.261ms
TCP connection attempts: 5 | Successful connections: 5 | Failed: 0 (0.00%)
Nping done: 1 IP address pinged in 4.01 seconds
