### ISSUE TITLE
error in check 9

### ISSUE THREAD

**Issue by jacontre-c** [CiscoDevNet/sure#16]
ERROR:the JSON object must be str, not 'NoneType'
Traceback (most recent call last):
  File "sure.py", line 3821, in <module>
    es_indices_est = json.loads(getRequestpy3(version_tuple,vmanage_lo_ip, jsessionid, 'management/elasticsearch/index/size/estimate', args.vmanage_port, tokenid))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))

**Comment by rukapse** [comment]
Check if the API is retuning None.

**Comment by rukapse** [comment]
20.6 since getRequestpy3

**Comment by rukapse** [comment]
API retrieving incorrect data.
After this scope should be able to use the API
https://cdetsng.cisco.com/summary/#/defect/CSCwa94955

Meanwhile, do curl to get ES Indices data

**Comment by ProsperousHeart** [comment]
This is being worked on under internal Jira CEADETT-136. No ETA as of yet.

**Comment by rukapse** [comment]
Jira Ticket
https://jira-eng-sjc4.cisco.com/jira/browse/SDWANAURA-49

**Comment by rukapse** [comment]
Assigned to Harshal Khairnar, waiting for him to get a git account

**Comment by rukapse** [comment]
curl -XGET http://localhost:9200/_cat/indices/ -u elasticsearch:s3cureElast1cPass

**Comment by rukapse** [comment]
this is an example of approute

ELLY_vManage:~# curl -XGET http://localhost:9200/_cat/indices/ -u elasticsearch:s3cureElast1cpass | grep approute
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100green open approutestatsstatistics_2022_07_23t04_01_14                QLfttGEVQy6iPnnxzsvujw 1 0 36925132     0   8.7gb   8.7gb
10green open approutestatsstatistics_2022_07_24t15_46_14                Wp8QJitITLKOdFdpQNDqmA 1 0 22491734     0   5.3gb   5.3gb
24green open approutestatsstatistics_routing_summary_2022_07_28t12_31   SBcNHl1tQ7iVDIgZdqw7EA 1 0       75     0  35.6kb  35.6kb
0  100 1green open approutestatsstatistics_2022_07_25t12_01_14                hLrufu9yTtiN8XVnOTMWeQ 1 0 41307294     0   9.8gb   9.8gb
0240    0     0  29595      0 --:--:-- --:--:-- --:--:-- 29595
green open approutestatsstatistics_2022_07_27t22_01_14                oIJXgQjXTICm2lzgUcepiA 1 0 17208862     0   4.1gb   4.1gb
green open approutestatsstatistics_2022_07_27t00_16_14                RevGfK90QTmOpULGcJndKg 1 0 24616698     0   5.9gb   5.9gb
green open approutestatsstatistics_transport_summary_2022_07_28t12_31 o1Hv7lyJRqmt82VWHK1pyQ 1 0      744     0 109.8kb 109.8kb


add all accumulated in 1 day from the files like here each day 1 file created and size are 5-6 GB Approx


you see the date like 2022_07_23t04_01_14
so here you see only 1 file created in 1 day
sometime it will be 5 file created in 1 day , so we need to add the volume of all 5 and get estimate
today will be incomplete, it should be last 2-3 days and than average

DPI stopped from 20.6

**Comment by rukapse** [comment]
Example of DPI and approute

vmanage:~$ curl --connect-timeout 6 --silent -XGET localhost:9200/_cat/indices/ -u elasticsearch:s3cureElast1cPass
green open approutestatsstatistics_2022_09_19t07_03_07                Jvc7GtZZSq6cJEDXUUAYmg 1 0  0 0   191b   191b
green open devicesystemstatusstatistics_2022_09_19t07_03_06           HlRACN1DQM-rVNk7ucHO6Q 1 0  0 0   191b   191b
green open approutestatsstatistics_routing_summary_2022_09_23t03_45   EEO279MxRz66iuSEwA8Z6g 1 0  0 0   162b   162b
green open alarm_2022_09_19t07_03_08                                  l2-tpp55Rg-xIJvbsYdGBQ 1 0  0 0   191b   191b
green open dpistatistics_application_summary_2022_09_23t03_45         SNHiN8cTRui19CEvxdOidQ 1 0  0 0   162b   162b
green open bridgeinterfacestatistics_2022_09_19t07_03_07              KGp5zCqQRUeSq7e2LqftrQ 1 0  0 0   191b   191b
green open bridgemacstatistics_2022_09_19t07_03_07                    zTRaukn6R2uIdpEGMRQiSA 1 0  0 0   191b   191b
green open deviceconfiguration_2022_09_19t07_03_06                    hkqIJqIwTJqvH2UkinmbRw 1 0  0 0   191b   191b
green open cloudxstatistics_2022_09_19t07_03_08                       c-qz5dndRna4OAOWH2RApQ 1 0  0 0   191b   191b
green open interfacestatistics_2022_09_19t07_03_06                    NEwcP7Y8TzOFpfpvPydgQg 1 0  0 0   191b   191b
green open deviceevents_2022_09_19t07_03_07                           fYJzqvt2RKuPRtRihQuRag 1 0  0 0   191b   191b
green open dpistatistics_2022_09_19t07_03_07                          9vZLMb2tRZyqzYDrIt9jMg 1 0  0 0   191b   191b
green open speedtest_2022_09_19t07_03_08                              crJj0Q0yQbO0AbmqhLMrgw 1 0  0 0   191b   191b
green open wlanclientinfostatistics_2022_09_19t07_03_07               c24jSiykQf6m3rIlFdh0kg 1 0  0 0   191b   191b
green open auditlog_2022_09_19t07_03_05                               IodWkqmXSiiJAoGEKTh4aA 1 0 57 0 45.8kb 45.8kb
green open approutestatsstatistics_transport_summary_2022_09_23t03_45 R4MAgS34T6KCrr14oz_Iyg 1 0 75 0 24.3kb 24.3kb
green open flowlogstatistics_2022_09_19t07_03_08                      KjXq0wYZS7ytb-qlGyl9Jw 1 0  0 0   191b   191b

**Comment by ssidoret** [comment]
Hi guys,

i have the same problem :
ERROR:the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "py3_sure.py", line 2320, in <module>
    es_indices_est = json.loads(getRequestpy3(version_tuple,vmanage_lo_ip, jsessionid, 'management/elasticsearch/index/size/estimate', args.vmanage_port, tokenid))
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

and i am not even able to run curl because of connection refused :

vManage:~$ curl -XGET http://localhost:9200/_cat/indices/ -u elasticsearch:s3cureElast1cpass | grep approute
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 9200: Connection refused

Can you help?
