### ISSUE TITLE
Authentication error if password contains special characters

### ISSUE THREAD

**Issue by jacontre-c** [CiscoDevNet/sure#2]
Tool may report JSESSION error, when password contains the sequence $$ or a +
Logs show:

```
Traceback (most recent call last):
File "sure.py", line 2460, in <module>
jsessionid = generateSessionID(vmanage_lo_ip, args.username, password, args.vmanage_port)
File "sure.py", line 210, in generateSessionID
jsessionid = (login[3].split('=')[1][0:-1])
IndexError: list index out of range

```

**Comment by jacontre-c** [comment]
Issue solved on release 1.0.5
