### ISSUE TITLE
Keyerror exception on 'timeRemainingForExpiration'

### ISSUE THREAD

**Issue by javcon** [CiscoDevNet/sure#29]
INFO:****Collecting Preliminary Data

ERROR:'timeRemainingForExpiration'
Traceback (most recent call last):
  File "sure.py", line 2499, in <module>
    controllers_info = controllersInfo(controllers)
  File "sure.py", line 327, in controllersInfo
    controllers_info[(device['host-name'])] = [(device['deviceType']),(device['deviceIP']),(device['version']) ,(device['reachability']),(device['globalState']),(device['timeRemainingForExpiration']), (device['state_vedgeList']) ]
KeyError: 'timeRemainingForExpiration'

**Comment by rukapse** [comment]
Hi Rugvedi,

Regarding - "https://github.com/CiscoDevNet/sure/issues/29", I had a chat with Arnab and ManiT on Friday and I also did further analysis. Based on the findings so far we can use one of the below show commands to fetch certificate validity date-time.

- show control local-properties certificate-not-valid-after
- show certificate validity

However, when we try to calculate the time difference in seconds in python it does not match exactly with the "timeRemainingForExpiration" value that is returned by API. But, we can still use the value calculated in python as approximate value.

**Comment by rukapse** [comment]
Regarding this issue, I think since "timeRemainingForExpiration" is related to the controller certificate it should be present in all the versions unless there is no certificate installed in a particular controller device. So, we may just have to add an exception-handling code to take care of this scenario.

**Comment by rukapse** [comment]
Since we are checking the Expiration dates for all the controllers in the network. It wont be possible to execute show commands on them in cases where the certificate is not installed.

**Comment by ProsperousHeart** [comment]
Jira for internal discussions is CEADETT-134

**Comment by rukapse** [comment]
Jira ticket
https://jira-eng-sjc4.cisco.com/jira/browse/SDWANAURA-42

**Comment by rukapse** [comment]
No, it won’t be needed. Simple: if user has ! In their password, that user won’t work in the first place

**Comment by rukapse** [comment]
1. This is a controller check, but since show commands cannot be remotely executed on the controllers, this check has to be moved vManage check. 

2. Replace the API with show commands to get the timeRemainingforExpiration 

      -           show control local-properties certificate-not-valid-after
      -           show certificate validity
