### ISSUE TITLE
Script fails ungracefully if configuration-db, statistics-db, or application-server are down

### ISSUE THREAD

**Issue by rukapse** [CiscoDevNet/sure#90]
Another issue I noticed is that if configuration-db, statistics-db, or application-server are down, the script will fail ungracefully and will not even reach this section of the AURA script. It calls to question if this check is really valuable and/or if it should be performed first. Just wanted to share my findings here.
 
Example:
 
INFO:Executing the script in Normal execution mode
INFO:Generating a JSessionID
INFO:Generating CSRF Token
INFO:****Collecting Preliminary Data
 
ERROR:the JSON object must be str, not 'NoneType'
Traceback (most recent call last):
  File "py3_sure.py", line 1922, in <module>
    controllers = json.loads(getRequestpy3(version_tuple, vmanage_lo_ip, jsessionid , 'system/device/controllers', args.vmanage_port, tokenid))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'

**Comment by rukapse** [comment]
Jira Ticket: https://jira-eng-sjc4.cisco.com/jira/browse/SDWANAURA-65
